# Generated by Django 4.1.4 on 2022-12-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitud',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitud',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
