# Generated by Django 4.1.4 on 2022-12-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_marker_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitud',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitud',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
